Improv/bb 20668
E-goi/EgoiPushLibraryAndroid pull request #26
Opened 2022-07-18 09:38 UTC by JoaoCGS

2022-08-12 09:48 UTC, dpereiraegoi requested changes

2022-08-12 09:48 UTC, dpereiraegoi commented on app/build.gradle
> +    implementation project(':EgoiPushLibrary')
Isto não está a chamar o projeto local?

2022-08-12 09:48 UTC, dpereiraegoi commented on app/src/main/java/com/egoiapp/egoipushlibraryandroid/MainActivity.kt
> +            apiKey = "9359df7f635ece99bc0aa934a1f831a2de49e40e",
remover apikey real

2022-08-16 15:18 UTC, JoaoCGS commented on app/build.gradle
> +    implementation project(':EgoiPushLibrary')
Foi feito o commit dos dados de dev sem querer

2022-08-16 15:18 UTC, JoaoCGS commented on app/src/main/java/com/egoiapp/egoipushlibraryandroid/MainActivity.kt
> +            apiKey = "9359df7f635ece99bc0aa934a1f831a2de49e40e",
Foi feito o commit dos dados de dev sem querer

2022-08-17 14:55 UTC, merged